package constants

const (
	noneLayout    = "none"    // Hidden
	defaultLayout = "default" // Default tab and product page
	advanceLayout = "advance" // Advance tab and product page
	productLayout = "product" // Only product page
)

var (
	ElementalConstants elementalContants = elementalContants{
		List: ElementalContantStruct{
			ID:       0,
			Name:     "list",
			Url:      "lists",
			IsActive: true,
			Metadata: Metadata{
				IsActive:     true,
				IsSearchable: true,
				Functionalities: Functionalities{
					IsTemplateHidden:        true,
					IsTitleLowercase:        false,
					HasTemplatePlaceholders: false,
					HasTemplateStyles:       false,
					HasTemplateAllStyles:    false,
					HasTypeId:               false,
					CanUse:                  false,
				},
				Validation: Validation{
					CanDuplicatedTitle:   true,
					LengthTitleMin:       3,
					LengthTitleMax:       200,
					LengthDescriptionMin: 0,
					LengthDescriptionMax: 10000,
					// LengthTemplateMin:    0,		// List does not have template
					// LengthTemplateMax:    10000,	// List does not have template
					// LengthTopicsMin:      1,		// List does not have topics
					// LengthTopicsMax:      3,		// List does not have topics
					PermittedTypeIds:        []int{},    // List does not have type
					PermittedFileExtensions: []string{}, // List does not have attachments
				},
				Layout: Layout{
					Title:                 defaultLayout,
					Avatar:                defaultLayout,
					Description:           defaultLayout,
					SaveToList:            noneLayout,
					Template:              noneLayout,
					Attachment:            noneLayout, // List does not have attachments
					IsPrivate:             defaultLayout,
					Comments:              defaultLayout,
					Reviews:               defaultLayout,
					IsPremium:             defaultLayout,
					Type:                  noneLayout,
					TopicIds:              productLayout,
					CommandSlash:          noneLayout,
					Source:                noneLayout,
					CommandKey:            noneLayout,
					ImagesCover:           defaultLayout,
					Images:                noneLayout,
					VideoUrl:              advanceLayout,
					HowtoSection:          advanceLayout,
					FeaturedReview:        advanceLayout,
					CompanySection:        advanceLayout,
					FeaturesSection:       advanceLayout,
					TestimonialSection:    advanceLayout,
					TweetsSection:         advanceLayout,
					AdditionalTextSection: advanceLayout,
				},
			},
		},
		Prompt: ElementalContantStruct{
			ID:       1,
			Name:     "prompt",
			Url:      "prompts",
			IsActive: true,
			Metadata: Metadata{
				IsActive:     true,
				IsSearchable: true,
				Functionalities: Functionalities{
					IsTemplateHidden:        true,
					IsTitleLowercase:        false,
					HasTemplatePlaceholders: true,
					HasTypeId:               true,
					CanUse:                  true,
				},
				Validation: Validation{
					CanDuplicatedTitle:      true,
					LengthTitleMin:          3,
					LengthTitleMax:          200,
					LengthDescriptionMin:    0,
					LengthDescriptionMax:    10000,
					LengthTemplateMin:       10,
					LengthTemplateMax:       40000,
					LengthTopicsMin:         1,
					LengthTopicsMax:         3,
					PermittedTypeIds:        []int{1, 2, 3, 4},
					PermittedFileExtensions: []string{"*"},
				},
				Layout: Layout{
					Title:                 defaultLayout,
					Avatar:                defaultLayout,
					Description:           defaultLayout,
					SaveToList:            defaultLayout,
					Template:              defaultLayout,
					Attachment:            advanceLayout,
					IsPrivate:             defaultLayout,
					Comments:              defaultLayout,
					Reviews:               defaultLayout,
					IsPremium:             defaultLayout,
					Type:                  defaultLayout,
					TopicIds:              defaultLayout,
					CommandSlash:          noneLayout,
					Source:                noneLayout,
					CommandKey:            advanceLayout,
					ImagesCover:           defaultLayout,
					Images:                advanceLayout,
					VideoUrl:              advanceLayout,
					HowtoSection:          advanceLayout,
					FeaturedReview:        advanceLayout,
					CompanySection:        advanceLayout,
					FeaturesSection:       advanceLayout,
					TestimonialSection:    advanceLayout,
					TweetsSection:         advanceLayout,
					AdditionalTextSection: advanceLayout,
				},
			},
		},
		Snippet: ElementalContantStruct{
			ID:       2,
			Name:     "snippet",
			Url:      "snippets",
			IsActive: true,
			Metadata: Metadata{
				IsActive:     true,
				IsSearchable: false,
				Functionalities: Functionalities{
					IsTemplateHidden:        false,
					IsTitleLowercase:        true,
					HasTemplatePlaceholders: false,
					HasTemplateStyles:       true,
					HasTemplateAllStyles:    false,
					HasTypeId:               false,
					CanUse:                  false,
				},
				Validation: Validation{
					CanDuplicatedTitle:      true,
					LengthTitleMin:          3,
					LengthTitleMax:          200,
					LengthDescriptionMin:    0,
					LengthDescriptionMax:    10000,
					LengthTemplateMin:       1,
					LengthTemplateMax:       100000,
					LengthTopicsMin:         0,
					LengthTopicsMax:         3,
					PermittedTypeIds:        []int{15},
					PermittedFileExtensions: []string{"*"},
				},
				Layout: Layout{
					Title:                 defaultLayout,
					Avatar:                advanceLayout,
					Description:           advanceLayout,
					SaveToList:            defaultLayout,
					Template:              defaultLayout,
					Attachment:            advanceLayout,
					IsPrivate:             defaultLayout,
					Comments:              defaultLayout,
					Reviews:               defaultLayout,
					IsPremium:             noneLayout,
					Type:                  noneLayout,
					TopicIds:              advanceLayout,
					CommandSlash:          defaultLayout,
					Source:                noneLayout,
					CommandKey:            noneLayout,
					ImagesCover:           advanceLayout,
					Images:                advanceLayout,
					VideoUrl:              advanceLayout,
					HowtoSection:          advanceLayout,
					FeaturedReview:        advanceLayout,
					CompanySection:        advanceLayout,
					FeaturesSection:       advanceLayout,
					TestimonialSection:    advanceLayout,
					TweetsSection:         advanceLayout,
					AdditionalTextSection: advanceLayout,
				},
			},
		},
		Document: ElementalContantStruct{
			ID:       3,
			Name:     "document",
			Url:      "documents",
			IsActive: true,
			Metadata: Metadata{
				IsActive:     true,
				IsSearchable: false,
				Functionalities: Functionalities{
					IsTemplateHidden:        false,
					IsTitleLowercase:        false,
					HasTemplatePlaceholders: false,
					HasTemplateStyles:       true,
					HasTemplateAllStyles:    true,
					HasTypeId:               false,
					CanUse:                  false,
				},
				Validation: Validation{
					CanDuplicatedTitle:      true,
					LengthTitleMin:          3,
					LengthTitleMax:          200,
					LengthDescriptionMin:    0,
					LengthDescriptionMax:    10000,
					LengthTemplateMin:       1,
					LengthTemplateMax:       100000,
					LengthTopicsMin:         0,
					LengthTopicsMax:         3,
					PermittedTypeIds:        []int{16},
					PermittedFileExtensions: []string{"*"},
				},
				Layout: Layout{
					Title:                 defaultLayout,
					Avatar:                advanceLayout,
					Description:           advanceLayout,
					SaveToList:            defaultLayout,
					Template:              defaultLayout,
					Attachment:            advanceLayout,
					IsPrivate:             defaultLayout,
					Comments:              defaultLayout,
					Reviews:               defaultLayout,
					IsPremium:             noneLayout,
					Type:                  noneLayout,
					TopicIds:              advanceLayout,
					CommandSlash:          noneLayout,
					Source:                noneLayout,
					CommandKey:            noneLayout,
					ImagesCover:           advanceLayout,
					Images:                advanceLayout,
					VideoUrl:              advanceLayout,
					HowtoSection:          advanceLayout,
					FeaturedReview:        advanceLayout,
					CompanySection:        advanceLayout,
					FeaturesSection:       advanceLayout,
					TestimonialSection:    advanceLayout,
					TweetsSection:         advanceLayout,
					AdditionalTextSection: advanceLayout,
				},
			},
		},
		Output: ElementalContantStruct{
			ID:       4,
			Name:     "output",
			Url:      "outputs",
			IsActive: false,
			Metadata: Metadata{
				IsActive:     false,
				IsSearchable: false,
				Functionalities: Functionalities{
					IsTemplateHidden:        false,
					IsTitleLowercase:        false,
					HasTemplatePlaceholders: false,
					HasTemplateStyles:       true,
					HasTemplateAllStyles:    false,
					HasTypeId:               true,
					CanUse:                  false,
				},
				Validation: Validation{
					CanDuplicatedTitle:      true,
					LengthTitleMin:          3,
					LengthTitleMax:          200,
					LengthDescriptionMin:    0,
					LengthDescriptionMax:    10000,
					LengthTemplateMin:       1,
					LengthTemplateMax:       100000,
					LengthTopicsMin:         0,
					LengthTopicsMax:         0,
					PermittedTypeIds:        []int{5, 6, 7, 8},
					PermittedFileExtensions: []string{"*"},
				},
				Layout: Layout{
					Title:                 defaultLayout,
					Avatar:                defaultLayout,
					Description:           advanceLayout,
					SaveToList:            defaultLayout,
					Template:              defaultLayout,
					Attachment:            advanceLayout,
					IsPrivate:             defaultLayout,
					Comments:              defaultLayout,
					Reviews:               defaultLayout,
					IsPremium:             noneLayout,
					Type:                  defaultLayout,
					TopicIds:              noneLayout,
					CommandSlash:          noneLayout,
					Source:                defaultLayout,
					CommandKey:            noneLayout,
					ImagesCover:           advanceLayout,
					Images:                advanceLayout,
					VideoUrl:              advanceLayout,
					HowtoSection:          advanceLayout,
					FeaturedReview:        advanceLayout,
					CompanySection:        advanceLayout,
					FeaturesSection:       advanceLayout,
					TestimonialSection:    advanceLayout,
					TweetsSection:         advanceLayout,
					AdditionalTextSection: advanceLayout,
				},
			},
		},
		Automation: ElementalContantStruct{
			ID:       5,
			Name:     "automation",
			Url:      "automations",
			IsActive: true,
			Metadata: Metadata{
				IsActive:     true,
				IsSearchable: false,
				Functionalities: Functionalities{
					IsTemplateHidden:        false,
					IsTitleLowercase:        false,
					HasTemplatePlaceholders: false,
					HasTemplateStyles:       false,
					HasTemplateAllStyles:    false,
					HasTypeId:               true,
					CanUse:                  false,
				},
				Validation: Validation{
					CanDuplicatedTitle:      true,
					LengthTitleMin:          3,
					LengthTitleMax:          200,
					LengthDescriptionMin:    0,
					LengthDescriptionMax:    10000,
					LengthTemplateMin:       0,
					LengthTemplateMax:       100000,
					LengthTopicsMin:         0,
					LengthTopicsMax:         3,
					PermittedTypeIds:        []int{9, 10, 11, 12, 13, 14},
					PermittedFileExtensions: []string{".json"},
				},
				Layout: Layout{
					Title:                 defaultLayout,
					Avatar:                defaultLayout,
					Description:           defaultLayout,
					SaveToList:            defaultLayout,
					Template:              noneLayout,
					Attachment:            defaultLayout,
					IsPrivate:             defaultLayout,
					Comments:              defaultLayout,
					Reviews:               defaultLayout,
					IsPremium:             defaultLayout,
					Type:                  defaultLayout,
					TopicIds:              defaultLayout,
					CommandSlash:          noneLayout,
					Source:                noneLayout,
					CommandKey:            noneLayout,
					ImagesCover:           defaultLayout,
					Images:                advanceLayout,
					VideoUrl:              advanceLayout,
					HowtoSection:          advanceLayout,
					FeaturedReview:        advanceLayout,
					CompanySection:        advanceLayout,
					FeaturesSection:       advanceLayout,
					TestimonialSection:    advanceLayout,
					TweetsSection:         advanceLayout,
					AdditionalTextSection: advanceLayout,
				},
			},
		},
		Course: ElementalContantStruct{
			ID:       6,
			Name:     "course",
			Url:      "courses",
			IsActive: false,
			Metadata: Metadata{
				IsActive:     false,
				IsSearchable: false,
				Functionalities: Functionalities{
					IsTemplateHidden:        false,
					IsTitleLowercase:        false,
					HasTemplatePlaceholders: false,
					HasTemplateStyles:       true,
					HasTemplateAllStyles:    false,
					HasTypeId:               false,
					CanUse:                  false,
				},
				Validation: Validation{
					CanDuplicatedTitle:      true,
					LengthTitleMin:          3,
					LengthTitleMax:          200,
					LengthDescriptionMin:    0,
					LengthDescriptionMax:    10000,
					LengthTemplateMin:       1,
					LengthTemplateMax:       100000,
					LengthTopicsMin:         1,
					LengthTopicsMax:         3,
					PermittedTypeIds:        []int{},
					PermittedFileExtensions: []string{"*"},
				},
				Layout: Layout{
					Title:                 defaultLayout,
					Avatar:                defaultLayout,
					Description:           defaultLayout,
					SaveToList:            defaultLayout,
					Template:              defaultLayout,
					Attachment:            defaultLayout,
					IsPrivate:             defaultLayout,
					Comments:              defaultLayout,
					Reviews:               defaultLayout,
					IsPremium:             defaultLayout,
					Type:                  noneLayout,
					TopicIds:              defaultLayout,
					CommandSlash:          noneLayout,
					Source:                noneLayout,
					CommandKey:            noneLayout,
					ImagesCover:           defaultLayout,
					Images:                defaultLayout,
					VideoUrl:              defaultLayout,
					HowtoSection:          defaultLayout,
					FeaturedReview:        defaultLayout,
					CompanySection:        advanceLayout,
					FeaturesSection:       defaultLayout,
					TestimonialSection:    defaultLayout,
					TweetsSection:         defaultLayout,
					AdditionalTextSection: defaultLayout,
				},
			},
		},
		Table: ElementalContantStruct{
			ID:       7,
			Name:     "table",
			Url:      "tables",
			IsActive: true,
			Metadata: Metadata{
				IsActive:     true,
				IsSearchable: false,
				Functionalities: Functionalities{
					IsTemplateHidden:        false,
					IsTitleLowercase:        false,
					HasTemplatePlaceholders: false,
					HasTemplateStyles:       false,
					HasTypeId:               true,
					CanUse:                  false,
				},
				Validation: Validation{
					CanDuplicatedTitle:      true,
					LengthTitleMin:          3,
					LengthTitleMax:          200,
					LengthDescriptionMin:    0,
					LengthDescriptionMax:    10000,
					LengthTemplateMin:       0,
					LengthTemplateMax:       1,
					LengthTopicsMin:         0,
					LengthTopicsMax:         3,
					PermittedTypeIds:        []int{17},
					PermittedFileExtensions: []string{"*"},
				},
				Layout: Layout{
					Title:                 defaultLayout,
					Avatar:                advanceLayout,
					Description:           advanceLayout,
					SaveToList:            defaultLayout,
					Template:              defaultLayout,
					Attachment:            advanceLayout,
					IsPrivate:             defaultLayout,
					Comments:              defaultLayout,
					Reviews:               defaultLayout,
					IsPremium:             noneLayout,
					Type:                  noneLayout,
					TopicIds:              advanceLayout,
					CommandSlash:          noneLayout,
					Source:                noneLayout,
					CommandKey:            noneLayout,
					ImagesCover:           advanceLayout,
					Images:                advanceLayout,
					VideoUrl:              advanceLayout,
					HowtoSection:          advanceLayout,
					FeaturedReview:        advanceLayout,
					CompanySection:        advanceLayout,
					FeaturesSection:       advanceLayout,
					TestimonialSection:    advanceLayout,
					TweetsSection:         advanceLayout,
					AdditionalTextSection: advanceLayout,
				},
			},
		},
		Cell: ElementalContantStruct{
			ID:       8,
			Name:     "cell",
			Url:      "cells",
			IsActive: true,
			Metadata: Metadata{
				IsActive:     false,
				IsSearchable: false,
				Functionalities: Functionalities{
					IsTemplateHidden:        false,
					IsTitleLowercase:        false,
					HasTemplatePlaceholders: false,
					HasTemplateStyles:       true,
					HasTypeId:               true,
					CanUse:                  false,
				},
				Validation: Validation{
					CanDuplicatedTitle:      true,
					LengthTitleMin:          3,
					LengthTitleMax:          200,
					LengthDescriptionMin:    0,
					LengthDescriptionMax:    10000,
					LengthTemplateMin:       0,
					LengthTemplateMax:       10000,
					LengthTopicsMin:         0,
					LengthTopicsMax:         3,
					PermittedTypeIds:        []int{18},
					PermittedFileExtensions: []string{"*"},
				},
				Layout: Layout{
					Title:                 defaultLayout,
					Avatar:                advanceLayout,
					Description:           advanceLayout,
					SaveToList:            defaultLayout,
					Template:              defaultLayout,
					Attachment:            advanceLayout,
					IsPrivate:             defaultLayout,
					Comments:              defaultLayout,
					Reviews:               defaultLayout,
					IsPremium:             noneLayout,
					Type:                  noneLayout,
					TopicIds:              advanceLayout,
					CommandSlash:          noneLayout,
					Source:                noneLayout,
					CommandKey:            noneLayout,
					ImagesCover:           advanceLayout,
					Images:                advanceLayout,
					VideoUrl:              advanceLayout,
					HowtoSection:          advanceLayout,
					FeaturedReview:        advanceLayout,
					CompanySection:        advanceLayout,
					FeaturesSection:       advanceLayout,
					TestimonialSection:    advanceLayout,
					TweetsSection:         advanceLayout,
					AdditionalTextSection: advanceLayout,
				},
			},
		},
	}
)

func init() {
	ElementalConstants.ElementalsArray = []ElementalContantStruct{
		ElementalConstants.List,
		ElementalConstants.Prompt,
		ElementalConstants.Snippet,
		ElementalConstants.Document,
		ElementalConstants.Output,
		ElementalConstants.Automation,
		ElementalConstants.Course,
		ElementalConstants.Table,
		ElementalConstants.Cell,
	}
}
